### ISSUE TITLE
文本下载python下载器 下载不了东西

### ISSUE THREAD

**Issue by falali009** [staugur/grab_huaban_board#11]
https://hbimg.huabanimg.com/8fc6e4dc2f80bf9674496a2f1dec84c75fa5f8ff9befe-c2F5kv

以上诗油猴抓取的url

**Comment by falali009** [comment]
有木有python3版本喵

**Comment by staugur** [comment]
瞅瞅~~
兼容3也不难，

**Comment by staugur** [comment]
花瓣网又拍云域名变了，忘记改了，现在全改了，测试可以下载。

另，py3基本兼容了~

**Comment by falali009** [comment]
谢谢 大神
