### ISSUE TITLE
5.04的版本下下来的图大半都变成同一张锁的图了

### ISSUE THREAD

**Issue by reimu1234** [staugur/grab_huaban_board#12]
好像最近增加了上锁的机制
请问有办法解决吗

**Comment by staugur** [comment]
这是花瓣网的问题。

花瓣网国庆左右升级系统，现在放出的版本，除了自己的画板，其他人的都锁了，估计得等官方开放解锁。

**Comment by reimu1234** [comment]
> 这是花瓣网的问题。
> 
> 花瓣网国庆左右升级系统，现在放出的版本，除了自己的画板，其他人的都锁了，估计得等官方开放解锁。

网页登录之后不是可以看到吗，为什么爬虫模拟登录就不行😂

**Comment by staugur** [comment]
是这样吗？我登录看别人的也还是加锁的。

**Comment by reimu1234** [comment]
> 是这样吗？我登录看别人的也还是加锁的。

emm我是看自己的

**Comment by staugur** [comment]
所以你用脚本下载自己的应该没锁，下别人的有
