### ISSUE TITLE
can‘t install grab_huaban_board.py

### ISSUE THREAD

**Issue by misaka123456** [staugur/grab_huaban_board#3]
>python grab_huaban_board.py install

  File "grab_huaban_board.py", line 22
    print '\033[92m{}\033[0m'.format(str(msg))
                            ^
SyntaxError: invalid syntax

**Comment by staugur** [comment]
Your python version?  如果是3+，那确实是这个语法错误，py3 print需要括号

**Comment by misaka123456** [comment]
我的确实是3+版本   这就很气

**Comment by staugur** [comment]
print ""改为print("")
