### ISSUE TITLE
由于url重定向导致的 登录时提示“邮箱或手机号不能为空”

### ISSUE THREAD

**Issue by othorizon** [staugur/grab_huaban_board#9]
baseUrl 是不是应该改为 'http://huaban.com' ？
原有的 url已经被重定向了，而且会导致 登录时提示“邮箱或手机号不能为空”。
没怎么用过python，不太清楚requests是怎么处理重定向问题的，以及为什么会导致登录时的表单参数提交失败。
大佬可以帮忙解答一下吗？

**Comment by staugur** [comment]
查看中

**Comment by staugur** [comment]
更新下代码重试看看

**Comment by othorizon** [comment]
> 更新下代码重试看看

ok 没问题了  ^ ^
